# Generated by Django 2.2.2 on 2019-10-30 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191030_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 30, 13, 35, 0, 357651), verbose_name='date commented'),
        ),
    ]
