# Generated by Django 2.1.1 on 2019-10-27 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191027_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 27, 9, 59, 16, 619245), verbose_name='date commented'),
        ),
    ]
